<?php
/**
 * Pearldrop theme.
 *
 * Generated by build/build.py — do not edit by hand; edit the generator.
 *
 * The one job that matters here: the stylesheet and the scripts are enqueued
 * ONCE, site-wide. They are not pasted into page content. That means the
 * browser caches them across the whole site, and changing the menu is one file
 * in one place rather than an edit on every page.
 */

if (!defined('ABSPATH')) { exit; }

const PEARLDROP_VER = '1.0.0';

function pearldrop_assets() {
    $uri = get_template_directory_uri();
    $dir = get_template_directory();

    // fonts first: self-hosted, so no third-party request in the critical path
    wp_enqueue_style('pearldrop-fonts', $uri . '/assets/fonts.css', [], PEARLDROP_VER);
    wp_enqueue_style('pearldrop', $uri . '/assets/site.css', ['pearldrop-fonts'], PEARLDROP_VER);

    // page-specific styles, only on the page that needs them
    $page_css = [
        'services/aerial-drone-video-production' => 'page-services-aerial-drone-video-production.css',
    ];
    $slug = trim(parse_url(add_query_arg([]), PHP_URL_PATH) ?: '', '/');
    if (isset($page_css[$slug]) && file_exists($dir . '/assets/' . $page_css[$slug])) {
        wp_enqueue_style('pearldrop-page', $uri . '/assets/' . $page_css[$slug],
                         ['pearldrop'], PEARLDROP_VER);
    }

    wp_enqueue_script('pearldrop', $uri . '/assets/site.js', [], PEARLDROP_VER, true);

    // the scroll-scrubbed frame sequence is only on the homepage
    if (is_front_page()) {
        wp_enqueue_script('pearldrop-hero', $uri . '/assets/hero.js', [], PEARLDROP_VER, true);
    }
}
add_action('wp_enqueue_scripts', 'pearldrop_assets');

/** Preload the two faces above the fold, so the headline does not swap late. */
function pearldrop_preload() {
    $uri = get_template_directory_uri();
    foreach (['anton-400-latin.woff2', 'inter-400-latin.woff2'] as $f) {
        printf('<link rel="preload" as="font" type="font/woff2" href="%s/assets/fonts/%s" crossorigin>' . "\n",
               esc_url($uri), esc_attr($f));
    }
}
add_action('wp_head', 'pearldrop_preload', 1);

function pearldrop_setup() {
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('responsive-embeds');
    add_theme_support('html5', ['style', 'script']);
    // the design supplies its own spacing and colour; core's defaults only fight it
    remove_theme_support('core-block-patterns');
}
add_action('after_setup_theme', 'pearldrop_setup');

/** WordPress ships its own global stylesheet; ours already covers everything. */
function pearldrop_trim() {
    wp_dequeue_style('wp-block-library-theme');
    wp_dequeue_style('classic-theme-styles');
}
add_action('wp_enqueue_scripts', 'pearldrop_trim', 20);
